server:
  port: 8087
database:
  uri: ${MONGO.URI}
  name: ${MONGO.NAME}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, env, beans

info:
  app1:
    name: User Service
    version: 1.0.0
  system:
    os: ${os.name}
    PID: ${PID}
    user-country: ${user.country}
    user-timezone: ${user.timezone}
