server:
  port: 8078
rabbit:
  host: ${RABBIT_HOST}
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    name: ${DB_MSG_NAME}
    username: ${DB_MSG_USERNAME}
    password: ${DB_MSG_PASSWORD}
    url: ${DB_MSG_URI}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: Message Service
    description: This microservice designed as responsible service for sending messages
    version: 1.0.0
  system:
    os: ${os.name}
    PID: ${PID}
    user-country: ${user.country}
    user-timezone: ${user.timezone}
