server:
  port: 8078

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    name: message-service-db
    username: ${db.msg.username}
    password: ${db.msg.password}
    url: ${db.msg.url}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: Message Service
    description: This microservice designed as responsible service for sending messages
    version: 1.0.0
  system:
    os: ${os.name}
    PID: ${PID}
    user-country: ${user.country}
    user-timezone: ${user.timezone}
